#include "gtest/gtest.h"
#include <string.h>
#include "tests/fff.h"
DEFINE_FFF_GLOBALS;


extern "C" {
// #undef LOG_TAG
// #include "../../utl/utl_thread.c"
#undef LOG_TAG
#include "../../utl/utl_log.c"
#undef LOG_TAG
#include "../../utl/utl_dbg.c"
#include "../../utl/utl_buf.c"
#include "../../utl/utl_push.c"
#include "../../utl/utl_time.c"
#include "../../utl/utl_int.c"
#include "../../utl/utl_str.c"
#undef LOG_TAG
#include "../../btc/btc.c"
#include "../../btc/btc_buf.c"
#include "../../btc/btc_extkey.c"
#include "../../btc/btc_keys.c"
#include "../../btc/btc_sw.c"
#include "../../btc/btc_sig.c"
#include "../../btc/btc_script.c"
#include "../../btc/btc_tx.c"
#include "../../btc/btc_tx_buf.c"
#include "../../btc/btc_crypto.c"
#include "../../btc/segwit_addr.c"
#include "../../btc/btc_segwit_addr.c"
#include "../../btc/btc_test_util.c"

#undef LOG_TAG
#include "ln_derkey.c"
#include "ln_derkey_ex.c"
#include "ln_msg_anno.c"
#include "ln_msg_close.c"
//#include "ln_msg_establish.c"
#include "ln_msg_normalope.c"
#include "ln_msg_setupctl.c"
#include "ln_node.c"
#include "ln_onion.c"
#include "ln_script.c"
#include "ln_noise.c"
#include "ln_signer.c"
#include "ln_invoice.c"
#include "ln_print.c"

#include "ln.c"
}

////////////////////////////////////////////////////////////////////////
//FAKE関数

FAKE_VOID_FUNC(ln_db_preimage_cur_close, void *);
FAKE_VALUE_FUNC(bool, ln_db_annocnlupd_load, utl_buf_t *, uint32_t *, uint64_t, uint8_t);
FAKE_VALUE_FUNC(bool, ln_db_preimage_del, const uint8_t *);
FAKE_VALUE_FUNC(bool, ln_db_preimage_cur_open, void **);
FAKE_VALUE_FUNC(bool, ln_db_preimage_cur_get, void *, bool *, ln_db_preimage_t *);
FAKE_VALUE_FUNC(bool, ln_db_channel_search, ln_db_func_cmp_t, void *);
FAKE_VALUE_FUNC(bool, ln_db_channel_search_readonly, ln_db_func_cmp_t, void *);
FAKE_VALUE_FUNC(bool, ln_db_phash_save, const uint8_t*, const uint8_t*, ln_comtx_output_type_t, uint32_t);
FAKE_VALUE_FUNC(bool, ln_db_preimage_search, ln_db_func_preimage_t, void*);
FAKE_VALUE_FUNC(bool, ln_db_preimage_set_expiry, void *, uint32_t);

FAKE_VALUE_FUNC(bool, ln_msg_open_channel_write, utl_buf_t *, const ln_msg_open_channel_t *);
FAKE_VALUE_FUNC(bool, ln_msg_open_channel_read, ln_msg_open_channel_t*, const uint8_t*, uint16_t);
FAKE_VALUE_FUNC(bool, ln_msg_accept_channel_write, utl_buf_t *, const ln_msg_accept_channel_t *);
FAKE_VALUE_FUNC(bool, ln_msg_accept_channel_read, ln_msg_accept_channel_t *, const uint8_t *, uint16_t );
FAKE_VALUE_FUNC(bool, ln_msg_funding_created_write, utl_buf_t *, const ln_msg_funding_created_t *);
FAKE_VALUE_FUNC(bool, ln_msg_funding_created_read, ln_msg_funding_created_t *, const uint8_t *, uint16_t );
FAKE_VALUE_FUNC(bool, ln_msg_funding_signed_write, utl_buf_t *, const ln_msg_funding_signed_t *);
FAKE_VALUE_FUNC(bool, ln_msg_funding_signed_read, ln_msg_funding_signed_t *, const uint8_t *, uint16_t );
typedef uint8_t (fake_sig_t)[LN_SZ_SIGNATURE];
FAKE_VALUE_FUNC(bool, ln_comtx_create_remote, const ln_channel_t *, ln_commit_tx_t *, ln_close_force_t *, fake_sig_t **);

////////////////////////////////////////////////////////////////////////

class ln_htlc_flag: public testing::Test {
protected:
    virtual void SetUp() {
        //utl_log_init_stderr();
        RESET_FAKE(ln_db_preimage_cur_close)
        RESET_FAKE(ln_db_annocnlupd_load)
        RESET_FAKE(ln_db_preimage_del)
        RESET_FAKE(ln_db_preimage_cur_open)
        RESET_FAKE(ln_db_preimage_cur_get)
        RESET_FAKE(ln_db_channel_search)
        RESET_FAKE(ln_db_channel_search_readonly)
        RESET_FAKE(ln_db_phash_save)
        RESET_FAKE(ln_db_preimage_search)
        RESET_FAKE(ln_db_preimage_set_expiry)
        RESET_FAKE(ln_msg_open_channel_read)
        RESET_FAKE(ln_msg_accept_channel_write)
        RESET_FAKE(ln_msg_accept_channel_read)
        RESET_FAKE(ln_msg_funding_created_write)
        RESET_FAKE(ln_msg_funding_created_read)
        RESET_FAKE(ln_msg_funding_signed_write)
        RESET_FAKE(ln_msg_funding_signed_read)
        RESET_FAKE(ln_comtx_create_remote)

        ln_comtx_create_remote_fake.return_val = true;
        utl_dbg_malloc_cnt_reset();
        btc_init(BTC_TESTNET, true);
    }

    virtual void TearDown() {
        ln_node_term();
        btc_term();
        ASSERT_EQ(0, utl_dbg_malloc_cnt());
    }

public:
    static void DumpBin(const uint8_t *pData, uint16_t Len)
    {
        for (uint16_t lp = 0; lp < Len; lp++) {
            printf("%02x", pData[lp]);
        }
        printf("\n");
    }
    static bool DumpCheck(const void *pData, uint32_t Len, uint8_t Fill)
    {
        bool ret = true;
        const uint8_t *p = (const uint8_t *)pData;
        for (uint32_t lp = 0; lp < Len; lp++) {
            if (p[lp] != Fill) {
                ret = false;
                break;
            }
        }
        return ret;
    }
    static void LnInit(ln_channel_t *pChannel)
    {
        ln_anno_prm_t annoprm;

        memset(pChannel, 0xcc, sizeof(ln_channel_t));
        pChannel->noise.p_handshake = NULL;
        annoprm.cltv_expiry_delta = 10;
        annoprm.htlc_minimum_msat = 1000;
        annoprm.fee_base_msat = 20;
        annoprm.fee_prop_millionths = 200;
        ln_init(pChannel, &annoprm, (ln_callback_t)0x123456);
        pChannel->commit_tx_local.dust_limit_sat = BTC_DUST_LIMIT;
        pChannel->commit_tx_local.htlc_minimum_msat = 0;
        pChannel->commit_tx_local.max_accepted_htlcs = 10;
        pChannel->commit_tx_remote.dust_limit_sat = BTC_DUST_LIMIT;
        pChannel->commit_tx_remote.htlc_minimum_msat = 0;
        pChannel->commit_tx_remote.max_accepted_htlcs = 10;
        pChannel->local_msat = 1000000;
        pChannel->remote_msat = 1000000;
        btc_tx_init(&pChannel->funding_tx.tx_data);
        utl_buf_init(&pChannel->funding_tx.wit_script);
        pChannel->p_callback = NULL;
    }
};

////////////////////////////////////////////////////////////////////////

TEST_F(ln_htlc_flag, htlc_flag_macro_offer_fulfill)
{
    ln_channel_t channel;
    LnInit(&channel);

    ln_update_add_htlc_t *p_htlc = &channel.cnl_add_htlc[0];
    ln_htlc_flag_t *p_flag = &p_htlc->stat.flag;

    //update_add_htlc準備
    p_flag->addhtlc = LN_ADDHTLC_SEND;

    ASSERT_TRUE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_add_htlc送信
    p_flag->updsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fulfill_htlc受信
    p_flag->comsend = 0;
    p_flag->revrecv = 0;
    p_flag->comrecv = 0;
    p_flag->revsend = 0;
    p_flag->delhtlc = LN_DELHTLC_FULFILL;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    ln_term(&channel);
}


TEST_F(ln_htlc_flag, htlc_flag_macro_offer_fail)
{
    ln_channel_t channel;
    LnInit(&channel);

    ln_update_add_htlc_t *p_htlc = &channel.cnl_add_htlc[0];
    ln_htlc_flag_t *p_flag = &p_htlc->stat.flag;

    //update_add_htlc準備
    p_flag->addhtlc = LN_ADDHTLC_SEND;

    ASSERT_TRUE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_add_htlc送信
    p_flag->updsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fail_htlc受信
    p_flag->comsend = 0;
    p_flag->revrecv = 0;
    p_flag->comrecv = 0;
    p_flag->revsend = 0;
    p_flag->delhtlc = LN_DELHTLC_FAIL;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    ln_term(&channel);
}


TEST_F(ln_htlc_flag, htlc_flag_macro_recv_fulfill)
{
    ln_channel_t channel;
    LnInit(&channel);

    ln_update_add_htlc_t *p_htlc = &channel.cnl_add_htlc[0];
    ln_htlc_flag_t *p_flag = &p_htlc->stat.flag;

    //update_add_htlc受信
    p_flag->addhtlc = LN_ADDHTLC_RECV;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fulfill_htlc準備
    p_flag->comsend = 0;
    p_flag->revrecv = 0;
    p_flag->comrecv = 0;
    p_flag->revsend = 0;
    p_flag->delhtlc = LN_DELHTLC_FULFILL;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fulfill_htlc送信
    p_flag->updsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_TRUE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    ln_term(&channel);
}


TEST_F(ln_htlc_flag, htlc_flag_macro_recv_fail)
{
    ln_channel_t channel;
    LnInit(&channel);

    ln_update_add_htlc_t *p_htlc = &channel.cnl_add_htlc[0];
    ln_htlc_flag_t *p_flag = &p_htlc->stat.flag;

    //update_add_htlc受信
    p_flag->addhtlc = LN_ADDHTLC_RECV;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fail_htlc準備
    p_flag->comsend = 0;
    p_flag->revrecv = 0;
    p_flag->comrecv = 0;
    p_flag->revsend = 0;
    p_flag->delhtlc = LN_DELHTLC_FAIL;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //update_fail_htlc送信
    p_flag->updsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_TRUE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed送信
    p_flag->comsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_TRUE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack受信
    p_flag->revrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //commitment_signed受信
    p_flag->comrecv = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_TRUE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    //revoke_and_ack送信
    p_flag->revsend = 1;

    ASSERT_FALSE(LN_HTLC_WILL_ADDHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_DELHTLC_SEND(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_OFFERED_HTLC(p_htlc));
    ASSERT_FALSE(LN_HTLC_WILL_COMSIG_SEND_RECEIVED_HTLC(p_htlc));

    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_LOCAL_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_LOCAL_FULFILL_SEND_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_DELHTLC_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_SEND_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_ADDHTLC_SEND_ENABLED(p_htlc));
    ASSERT_TRUE(LN_HTLC_REMOTE_DELHTLC_RECV_ENABLED(p_htlc));
    ASSERT_FALSE(LN_HTLC_REMOTE_FULFILL_RECV_ENABLED(p_htlc));

    ASSERT_FALSE(LN_HTLC_JUST_SEND_ADDHTLC_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FULFILL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_FAIL_AND_COMSIG(p_htlc));
    ASSERT_FALSE(LN_HTLC_JUST_SEND_MALFORMED_AND_COMSIG(p_htlc));

    ASSERT_FALSE(LN_HTLC_COMSIGING(p_htlc));
    ASSERT_TRUE(LN_HTLC_TEST_EXCLUSIVENESS(p_htlc));

    ln_term(&channel);
}


TEST_F(ln_htlc_flag, htlc_flag_offer_timeout)
{
    ln_channel_t channel;
    LnInit(&channel);

    ln_update_add_htlc_t *p_htlc = &channel.cnl_add_htlc[0];
    ln_htlc_flag_t *p_flag = &p_htlc->stat.flag;

    p_htlc->cltv_expiry = 100;
    p_flag->addhtlc = LN_ADDHTLC_SEND;
    p_flag->updsend = true;
    p_flag->comsend = true;
    p_flag->revrecv = true;
    p_flag->comrecv = true;
    p_flag->revsend = true;
    uint16_t bak = p_htlc->stat.bits;

    ASSERT_TRUE(ln_is_offered_htlc_timeout(&channel, 0, 100)); //just
    ASSERT_TRUE(ln_is_offered_htlc_timeout(&channel, 0, 101)); //pass
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 99)); //before

    p_flag->addhtlc = LN_ADDHTLC_NONE;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_flag->addhtlc = LN_ADDHTLC_RECV;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->delhtlc = LN_DELHTLC_FULFILL;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->updsend = false;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->comsend = false;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->revrecv = false;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->comrecv = false;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->revsend = false;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->fin_delhtlc = LN_DELHTLC_FULFILL;
    ASSERT_FALSE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;

    p_flag->reserved = 1;
    ASSERT_TRUE(ln_is_offered_htlc_timeout(&channel, 0, 100));
    p_htlc->stat.bits = bak;
}
