/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_nayuta_lightning_PtarmiganNative */

#ifndef _Included_co_nayuta_lightning_PtarmiganNative
#define _Included_co_nayuta_lightning_PtarmiganNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_nayuta_lightning_PtarmiganNative
 * Method:    ptarmStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_co_nayuta_lightning_PtarmiganNative_ptarmStart
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
